[project]
name = "diydl"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "openai>=1.106.1",
    "requests>=2.32.5",
    "scipy>=1.16.1",
    "torch>=2.8.0",
    "wikipedia-api>=0.8.1",
]
